- samples/apps/review/src/config.erl
- src/wf.erl
Use
```erlang
log_level() -> none.
```
for disabling logging and
```erlang
log_level() -> warning.
```
for logging warning level
> Log level implementation

- samples/apps/review/src/config.erl
- src/wf.erl
> Revert "Log level implementation"

- samples/apps/review/src/config.erl
- samples/sys.config
- src/wf.erl
Use
```erlang
log_level() -> none.
```
for disabling logging and
```erlang
log_level() -> warning.
```
for logging warning level
Also
```erlang
log_modules() -> any.
```
for logging all modules
> Log level / Log modules Any implementation

- src/endpoints/n2o_document.erl
- src/wf.erl
U can use as:
```erlang
main() -> wf:redirect({http,<<"/redirect_page">>}).
```
> + Http Redirect

- src/nitrogen/elements/element_tr.erl
Fix my previous mistype. Sorry for this.
> Fix element_tr

- include/wf.hrl
- src/nitrogen/elements/element_dtl.erl
It needs if we want to update dtl element
> Add js escape for dtl element

- src/formatters/wf_utils.erl
> simplify wf_utils:config

- src/endpoints/cowboy/n2o_cowboy.erl
- src/endpoints/cowboy/n2o_dynalo.erl
- src/endpoints/n2o_websocket.erl
- src/formatters/wf_utils.erl
- src/handlers/n2o_auth.erl
- src/handlers/n2o_query.erl
- src/handlers/n2o_session.erl
- src/nitrogen/actions/action_event.erl
- src/nitrogen/actions/action_jq.erl
- src/nitrogen/elements/element_command.erl
- src/nitrogen/elements/element_dtl.erl
- src/nitrogen/n2o_nitrogen.erl
- src/nitrogen/render/wf_render_actions.erl
- src/protocols/n2o_heart.erl
- src/protocols/n2o_rails.erl
Fix compile warnings
Fix typo in element_command.erl with #file{}
Get rid of unused code in element_dtl.erl
> Fix compile warnings

- doc/utf8.tex
utf_toByteArray => utf8_toByteArray
> fixed doc typo

- samples/apps/review/priv/templates/index.html
- samples/apps/review/priv/templates/login.html
- samples/apps/review/priv/templates/message.html
- remove external 
- add missing '>'
- add "" for values
- format lines
> Templates fix

- src/formatters/wf_convert.erl
- src/nitrogen/actions/action_event.erl
- src/nitrogen/n2o_nitrogen.erl
- src/nitrogen/render/wf_event.erl
- src/protocols/n2o_binary.erl
- src/protocols/n2o_client.erl
- src/protocols/n2o_rails.erl
- src/protocols/n2o_text.erl
Starts with 30% on medium interactivity page.
> More fast event rendering.

- src/formatters/wf_convert.erl
- src/nitrogen/actions/action_event.erl
- src/nitrogen/n2o_nitrogen.erl
- src/nitrogen/render/wf_event.erl
- src/protocols/n2o_binary.erl
- src/protocols/n2o_client.erl
- src/protocols/n2o_rails.erl
- src/protocols/n2o_text.erl
> Revert "More fast event rendering."

- samples/rebar.config
Fix bug at start on debian-based OS
> Up to date fs dependency

- src/wf.erl
> temp_id generates a unique value again (only R18)

- samples/apps/review/rebar.config
Solve: /apps/review/src/main.erl:6: can't find include lib "db/include/db.hrl"
> Add library path

- priv/protocols/bert.js
Allows types: ArrayBuffer / Uint8Array / String
Speed fix for large binaries: Reduce Accumulator now is Uint8Array
> Binary fix

- src/protocols/n2o_file.erl
fix forget to write the last fiece of data introduced in deb87f6ffe9aa0f11011a76802289ff45dcd0d9d
> forget to write the last chunk

- priv/ftp.js
- priv/n2o.js
- priv/protocols/bert.js
For file-transfer or raw-partially protocols
> Encode binary as DataView

- priv/protocols/bert.js
- priv/utf8.js
```js
$ ./bert.sh 
OK: 0
OK: 1
OK: 2
OK: 3
OK: 4
OK: 5
OK: 6
OK: 7
OK: 8
OK: 9
OK: 10
OK: 11
OK: 12
OK: 13
OK: 14
OK: 15
OK: 16
OK: 17
OK: 18
OK: 19
```
> Bert bugfix

- include/wf.hrl
- priv/ftp.js
- priv/n2o.js
- src/protocols/n2o_file.erl
Minimal collision & custom filename bug fix
> Hash in Ftp

- include/wf.hrl
- priv/ftp.js
- priv/n2o.js
- src/protocols/n2o_file.erl
> Revert "Hash in Ftp"

- priv/protocols/bert.js
> Bert bignum gag

- doc/last.tex
> Fixed another one typo

- src/handlers/n2o_async.erl
```erlang
proc(timeout,#handler{}=H) -> {stop,normal,H};
```
> Stopping processes by timeouts

- src/wf.erl
> wf:remove/1

- mix.exs
* make version semver compatible
* add dependencies to mix.exs
> fix build process with mix

- mix.exs
the n2o application was not started when being build with mix
> add application section to mix.exs file

- src/handlers/n2o_syn.erl
Remove un-necessary syn:register call and fix pool unregistration.
> Fix pool reg and unreg

- doc/index.tex
- doc/protocols.tex
> Fixed typos in .tex files

- samples/rebar.config
- src/formatters/wf_convert.erl
- src/wf.erl
2x up to 3x faster,
wf:hte alias for wf:html_encode
> Fast and smile HTML encoder

- priv/n2o.js
> n2o.js: improve eval errors
